graph TD;
  src_index_ts --> _Users_gijela_Desktop_github_repo_gitingest_ts_src_core_git_ts;
  src_index_ts --> _Users_gijela_Desktop_github_repo_gitingest_ts_src_core_scanner_ts;
  src_index_ts --> _Users_gijela_Desktop_github_repo_gitingest_ts_src_utils_index_ts;
  src_index_ts --> _Users_gijela_Desktop_github_repo_gitingest_ts_src_core_errors_ts;
  _Users_gijela_Desktop_github_repo_gitingest_ts_src_core_git_ts --> _Users_gijela_Desktop_github_repo_gitingest_ts_src_core_errors_ts;
  _Users_gijela_Desktop_github_repo_gitingest_ts_src_core_git_ts --> _Users_gijela_Desktop_github_repo_gitingest_ts_src_utils_env_ts;
  _Users_gijela_Desktop_github_repo_gitingest_ts_src_core_scanner_ts --> _Users_gijela_Desktop_github_repo_gitingest_ts_src_types_index_ts;
  _Users_gijela_Desktop_github_repo_gitingest_ts_src_core_scanner_ts --> _Users_gijela_Desktop_github_repo_gitingest_ts_src_core_errors_ts;
  _Users_gijela_Desktop_github_repo_gitingest_ts_src_utils_index_ts --> _Users_gijela_Desktop_github_repo_gitingest_ts_src_types_index_ts;
